baseurl = "https://sodiu.me/"
theme = "angels-ladder"
languageCode = "ja"
title = "Naf-blog"
disqusShortname = "Naf-blog"
canonifyurls = true
publishdir = "public"
[Params]
mastodon = "https://otogamer.me/@naf"
github = "https://github.com/naaaaaaaaaaaf"
showsRSS = true
copyright = "Written by Naf"
